import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/dose_schedule.dart';
import '../models/interaction_result.dart';
import '../models/regimen_analysis.dart';
import '../models/safety_report.dart';
import '../models/user_medication.dart';
import 'dose_service.dart';

/// Aggregated material the pharmacist-handoff report renders.
class PharmacistReportData {
  const PharmacistReportData({
    required this.patientName,
    required this.generatedAt,
    required this.medications,
    required this.schedules,
    required this.safety,
    required this.analysis,
    required this.adherence,
  });

  final String patientName;
  final DateTime generatedAt;
  final List<UserMedication> medications;
  final List<DoseSchedule> schedules;
  final SafetyReport safety;
  final RegimenAnalysis analysis;
  final AdherenceSummary adherence;
}

/// Builds shareable handoff reports — a clinician-friendly plain-text version
/// for WhatsApp/SMS and a typeset PDF for printing.
class PharmacistReportBuilder {
  PharmacistReportBuilder._();

  /// Plain-text report. Wide enough to read in any chat client; uses ASCII
  /// dividers so paste-into-WhatsApp doesn't lose structure.
  static String buildText(PharmacistReportData data) {
    final buffer = StringBuffer();
    void section(String title) {
      buffer
        ..writeln()
        ..writeln('— $title —');
    }

    buffer
      ..writeln('MedGuard — Pharmacist Handoff Report')
      ..writeln('Patient: ${data.patientName}')
      ..writeln('Generated: ${_formatDateTime(data.generatedAt)}');

    section('Medications (${data.medications.length})');
    if (data.medications.isEmpty) {
      buffer.writeln('• None recorded.');
    } else {
      for (final med in data.medications) {
        final schedule = data.schedules.firstWhere(
          (s) => s.drugId == med.drugId,
          orElse: () => _emptySchedule(med),
        );
        final dose = schedule.id == 0
            ? '(no schedule)'
            : schedule.doseLabel == null
            ? schedule.frequency.label
            : '${schedule.doseLabel} · ${schedule.frequency.label}';
        buffer.writeln('• ${med.displayName} — $dose');
      }
    }

    section('Drug-drug interactions (${data.safety.drugInteractions.length})');
    if (data.safety.drugInteractions.isEmpty) {
      buffer.writeln('• None detected.');
    } else {
      final sorted = [...data.safety.drugInteractions]
        ..sort((a, b) => b.severityLevel.rank.compareTo(a.severityLevel.rank));
      for (final interaction in sorted) {
        buffer
          ..writeln(
            '• [${interaction.riskLevel.label.toUpperCase()} RISK] '
            '${interaction.drugAName} ↔ ${interaction.drugBName}',
          )
          ..writeln(
            '    Mechanism: ${interaction.mechanism ?? "—"}',
          )
          ..writeln(
            '    Clinical effect: ${interaction.effect ?? "—"}',
          );
      }
    }

    section('Duplicate therapy (${data.safety.duplicateTherapies.length})');
    if (data.safety.duplicateTherapies.isEmpty) {
      buffer.writeln('• None.');
    } else {
      for (final dup in data.safety.duplicateTherapies) {
        buffer.writeln(
          '• ${dup.drugAName} and ${dup.drugBName} — '
          'shared class: ${dup.category}',
        );
      }
    }

    section('Food interactions (${data.safety.foodInteractions.length})');
    if (data.safety.foodInteractions.isEmpty) {
      buffer.writeln('• None.');
    } else {
      for (final food in data.safety.foodInteractions) {
        buffer.writeln('• ${food.drugName}: ${food.description}');
      }
    }

    section('CYP450 metabolism cascades');
    if (data.analysis.cascades.isEmpty) {
      buffer.writeln('• None.');
    } else {
      for (final cascade in data.analysis.cascades) {
        buffer.writeln('• ${cascade.summary}');
      }
    }

    section('Regimen risk');
    buffer
      ..writeln('• Composite score: ${data.analysis.cumulativeScore}/100')
      ..writeln('• Band: ${data.analysis.band.label}');
    for (final line in data.analysis.contributors) {
      buffer.writeln('  – $line');
    }

    section('Adherence (last 7 days)');
    final adherence = data.adherence;
    if (adherence.scheduled == 0) {
      buffer.writeln('• No scheduled doses in the window.');
    } else {
      buffer
        ..writeln(
          '• ${adherence.adhered}/${adherence.scheduled} doses '
          '(${adherence.percentRounded}% on time)',
        )
        ..writeln(
          '• Taken: ${adherence.taken} · Late: ${adherence.late} · '
          'Skipped: ${adherence.skipped} · Missed: ${adherence.missed}',
        );
    }

    buffer
      ..writeln()
      ..writeln('Generated by MedGuard. Not a substitute for clinical review.');
    return buffer.toString();
  }

  /// Typeset PDF report. Uses the bundled Inter family if available, else
  /// falls back to PDF's built-in Helvetica.
  static Future<Uint8List> buildPdf(PharmacistReportData data) async {
    final document = pw.Document();
    final theme = await _buildTheme();

    document.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        theme: theme,
        margin: const pw.EdgeInsets.fromLTRB(36, 40, 36, 40),
        build: (context) => [
          _pdfHeader(data),
          pw.SizedBox(height: 18),
          _pdfSection(
            'Medications (${data.medications.length})',
            data.medications.isEmpty
                ? const ['None recorded.']
                : [
                    for (final med in data.medications)
                      _formatMedicationLine(med, data.schedules),
                  ],
          ),
          _pdfSection(
            'Drug-drug interactions '
            '(${data.safety.drugInteractions.length})',
            data.safety.drugInteractions.isEmpty
                ? const ['None detected.']
                : data.safety.drugInteractions
                    .map(_formatInteractionLine)
                    .toList(),
          ),
          _pdfSection(
            'Duplicate therapy '
            '(${data.safety.duplicateTherapies.length})',
            data.safety.duplicateTherapies.isEmpty
                ? const ['None.']
                : data.safety.duplicateTherapies
                    .map(
                      (d) =>
                          '${d.drugAName} and ${d.drugBName} — shared class: ${d.category}',
                    )
                    .toList(),
          ),
          _pdfSection(
            'Food interactions (${data.safety.foodInteractions.length})',
            data.safety.foodInteractions.isEmpty
                ? const ['None.']
                : data.safety.foodInteractions
                    .map((f) => '${f.drugName}: ${f.description}')
                    .toList(),
          ),
          _pdfSection(
            'CYP450 metabolism cascades',
            data.analysis.cascades.isEmpty
                ? const ['None.']
                : data.analysis.cascades.map((c) => c.summary).toList(),
          ),
          _pdfSection(
            'Regimen risk — ${data.analysis.band.label} '
            '(${data.analysis.cumulativeScore}/100)',
            data.analysis.contributors.isEmpty
                ? const ['No contributing factors.']
                : data.analysis.contributors,
          ),
          _pdfSection(
            'Adherence (last 7 days)',
            data.adherence.scheduled == 0
                ? const ['No scheduled doses in the window.']
                : [
                    '${data.adherence.adhered}/${data.adherence.scheduled} doses '
                        '(${data.adherence.percentRounded}% on time)',
                    'Taken ${data.adherence.taken} · Late ${data.adherence.late} · '
                        'Skipped ${data.adherence.skipped} · Missed ${data.adherence.missed}',
                  ],
          ),
          pw.SizedBox(height: 18),
          pw.Text(
            'Generated by MedGuard on ${_formatDateTime(data.generatedAt)}. '
            'Not a substitute for clinical review.',
            style: pw.TextStyle(
              fontSize: 9,
              color: PdfColors.grey700,
              fontStyle: pw.FontStyle.italic,
            ),
          ),
        ],
      ),
    );
    return document.save();
  }

  // ── PDF helpers ────────────────────────────────────────────────────────────

  static Future<pw.ThemeData> _buildTheme() async {
    // The PDF default theme is fine — Helvetica is built-in and predictable.
    return pw.ThemeData.withFont();
  }

  static pw.Widget _pdfHeader(PharmacistReportData data) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'MEDGUARD',
          style: pw.TextStyle(
            color: PdfColors.teal800,
            fontWeight: pw.FontWeight.bold,
            fontSize: 11,
            letterSpacing: 2,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          'Pharmacist Handoff Report',
          style: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 22,
          ),
        ),
        pw.SizedBox(height: 6),
        pw.Text(
          'Patient: ${data.patientName}',
          style: const pw.TextStyle(fontSize: 12),
        ),
        pw.Text(
          'Generated: ${_formatDateTime(data.generatedAt)}',
          style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
        ),
        pw.SizedBox(height: 8),
        pw.Container(height: 1, color: PdfColors.grey400),
      ],
    );
  }

  static pw.Widget _pdfSection(String title, List<String> lines) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 14),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title,
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.teal900,
            ),
          ),
          pw.SizedBox(height: 6),
          for (final line in lines)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 3),
              child: pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('• ', style: const pw.TextStyle(fontSize: 11)),
                  pw.Expanded(
                    child: pw.Text(
                      line,
                      style: const pw.TextStyle(fontSize: 11),
                    ),
                  ),
                ],
              ),
            ),
        ],
      ),
    );
  }

  // ── Formatting helpers ─────────────────────────────────────────────────────

  static String _formatMedicationLine(
    UserMedication med,
    List<DoseSchedule> schedules,
  ) {
    final schedule = schedules.firstWhere(
      (s) => s.drugId == med.drugId,
      orElse: () => _emptySchedule(med),
    );
    final dose = schedule.id == 0
        ? '(no schedule)'
        : schedule.doseLabel == null
            ? schedule.frequency.label
            : '${schedule.doseLabel} · ${schedule.frequency.label}';
    return '${med.displayName} — $dose';
  }

  static String _formatInteractionLine(InteractionResult interaction) {
    final mech = interaction.mechanism;
    final effect = interaction.effect;
    final detail = [
      if (mech != null && mech.isNotEmpty) 'mechanism: $mech',
      if (effect != null && effect.isNotEmpty) 'effect: $effect',
    ].join(' · ');
    return '[${interaction.riskLevel.label.toUpperCase()} RISK] '
        '${interaction.drugAName} + ${interaction.drugBName}'
        '${detail.isEmpty ? '' : ' — $detail'}';
  }

  static DoseSchedule _emptySchedule(UserMedication med) {
    return DoseSchedule(
      id: 0,
      userId: med.userId,
      drugId: med.drugId,
      drugName: med.drugName,
      amount: 0,
      unit: 'mg',
      frequency: DoseFrequency.asNeeded,
      timeSlots: const [],
      startDate: DateTime.now(),
      createdAt: DateTime.now(),
    );
  }

  static String _formatDateTime(DateTime dt) {
    String pad(int v) => v.toString().padLeft(2, '0');
    return '${dt.year}-${pad(dt.month)}-${pad(dt.day)} '
        '${pad(dt.hour)}:${pad(dt.minute)}';
  }
}
