// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFU05pagYx-EwQBF7WImE_q35LsypNvE',
    appId: '1:745899760331:web:661ba7e1d5ffee7181994e',
    messagingSenderId: '745899760331',
    projectId: 'medguard-fa943',
    authDomain: 'medguard-fa943.firebaseapp.com',
    storageBucket: 'medguard-fa943.firebasestorage.app',
    measurementId: 'G-2GG863GM0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9_ERQxaRU7FfN9-75pYaUrOMqmuDY0_s',
    appId: '1:745899760331:android:8ad033e820e7572381994e',
    messagingSenderId: '745899760331',
    projectId: 'medguard-fa943',
    storageBucket: 'medguard-fa943.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvGJ45VCZVipVu7aqWGI_tVT9mCngRglY',
    appId: '1:745899760331:ios:4e6a66f316a9a05a81994e',
    messagingSenderId: '745899760331',
    projectId: 'medguard-fa943',
    storageBucket: 'medguard-fa943.firebasestorage.app',
    iosBundleId: 'com.medguard.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvGJ45VCZVipVu7aqWGI_tVT9mCngRglY',
    appId: '1:745899760331:ios:4e6a66f316a9a05a81994e',
    messagingSenderId: '745899760331',
    projectId: 'medguard-fa943',
    storageBucket: 'medguard-fa943.firebasestorage.app',
    iosBundleId: 'com.medguard.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMFU05pagYx-EwQBF7WImE_q35LsypNvE',
    appId: '1:745899760331:web:cd07435f5e2dd3f881994e',
    messagingSenderId: '745899760331',
    projectId: 'medguard-fa943',
    authDomain: 'medguard-fa943.firebaseapp.com',
    storageBucket: 'medguard-fa943.firebasestorage.app',
    measurementId: 'G-SV22MT95E4',
  );
}
